apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hellow
    spec:
      containers:
      - name: hello-ctr
        image: nigelpoulton/pluralsight-docker-ci:latest
        ports:
        - containerPort: 8080

